baseurl = "https://fergarciafer.github.io/"
title = "Fernando Garcia"
copyright = "Copyright &copy; 2018 - Fernando Garcia"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "https-fergarciafer-github-io-1"

[author]
    name = "Fernando Garcia"
    github = "fergarciafer"
    gitlab = ""
    linkedin = "fernandomartingarcia"
    facebook = "fergarciafer"
    twitter = "fergarciafer"
    instagram = ""

[params]
    tagline = "A space for creative and technical writing"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
